from environs import Env

env: Env = Env()
env.read_env()
HS_ALGORITHM = env('HS_ALGORITHM')
SECRET_KEY=env('SECRET_KEY')


DB_HOST = env('DB_HOST')
DB_PORT = env('DB_PORT')
POSTGRES_DB = env('POSTGRES_DB')
POSTGRES_USER = env('POSTGRES_USER')
POSTGRES_PASSWORD = env('POSTGRES_PASSWORD')


SMTP_REPRESENTER = env('SMTP_REPRESENTER')
SMTP_HOST = env('SMTP_HOST')
SMTP_PORT = env('SMTP_PORT')
SMTP_USER = env('SMTP_USER')
SMTP_PASS = env('SMTP_PASS')
